# Description: Configuration file for the Project Back script & Create_tiles

# Tile size
tile_size: 400

# Tiles starting point
start_x: 0
start_y: 0

# Directory path where to output the tiles
tiles_path: 'tiles/'

# File path of the tiles dictionary that contains the tile name and the pixel coordinates
tiles_dic: 'tiles_dic.txt'

# Directory path of the input RGB images used to create the orthomosaic
images_path: 'rgb_images/'

# Path to save the output of the part of the image that contains the projected tiles
project_back_path: '/'

# Name of the tile to be projected
tile_names: tile2_9

